# Generated by Django 5.1.1 on 2025-04-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenresImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_covers/')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('christian', 'Christian'), ('romance', 'Romance'), ('how-to', 'How To'), ('illustration', 'Illustration'), ('mystery', 'Mystery'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('fantasy', 'Fantasy'), ('history', 'History'), ('biography', 'Biography')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
